CREATE TABLE MERCHANT_CATEGORY_CODE (
    ID INT PRIMARY KEY IDENTITY,
    MCC_CODE NVARCHAR(4) NOT NULL UNIQUE,
    BENEFIT_CATEGORY_ID INT,
    FOREIGN KEY (BENEFIT_CATEGORY_ID) REFERENCES BENEFIT_CATEGORY(ID)
);