CREATE TABLE MERCHANT_CATEGORY_CODE (
    ID INT PRIMARY KEY IDENTITY,
    MCCCODE NVARCHAR(4) NOT NULL UNIQUE,
    BENEFITCATEGORYID INT,
    FOREIGN KEY (BENEFITCATEGORYID) REFERENCES BENEFIT_CATEGORY(ID)
);