CREATE TABLE ACCOUNT (
    ID INT PRIMARY KEY IDENTITY,
    ACCOUNTNUMBER NVARCHAR(20) NOT NULL UNIQUE,
    BALANCEFOOD DECIMAL(18, 2) NOT NULL,
    BALANCEMEAL DECIMAL(18, 2) NOT NULL,
    BALANCECASH DECIMAL(18, 2) NOT NULL
);