CREATE TABLE ACCOUNT (
    ID INT PRIMARY KEY IDENTITY,
    ACCOUNT_NUMBER NVARCHAR(20) NOT NULL UNIQUE,
    BALANCE_FOOD DECIMAL(18, 2) NOT NULL,
    BALANCE_MEAL DECIMAL(18, 2) NOT NULL,
    BALANCE_CASH DECIMAL(18, 2) NOT NULL
);