CREATE TABLE TRANSACTION_LOG (
    ID INT PRIMARY KEY IDENTITY,
    ACCOUNT_ID INT NOT NULL,
    AMOUNT DECIMAL(18, 2) NOT NULL,
    MERCHANT NVARCHAR(255) NOT NULL,
    MCC_CODE NVARCHAR(4) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    AUTHORIZATION_CODE NVARCHAR(2) NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);