INSERT INTO MERCHANT (NAME, MCC_CODE, ACCOUNT_ID)
VALUES 
    ('UBER TRIP', '5411', NULL), 
    ('UBER EATS', '5412', 1),
    ('PAG*JoseDaSilva', '5811', NULL),
    ('PICPAY*BILHETEUNICO', '5812', NULL);