CREATE TABLE MERCHANT (
    ID INT PRIMARY KEY IDENTITY,
    ACCOUNT_ID INT,
    NAME NVARCHAR(255) NOT NULL UNIQUE, 
    MCC_CODE NVARCHAR(4) NOT NULL,
    FOREIGN KEY (MCC_CODE) REFERENCES MERCHANT_CATEGORY_CODE(MCC_CODE),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);